version: 2
updates:
- package-ecosystem: "gomod"
  directory: "/"
  schedule:
    interval: "weekly"
  labels:
  - kind/enhancement
  - reviewed/ok-to-test
- package-ecosystem: "docker"
  directory: "/"
  schedule:
    interval: "weekly"
  labels:
  - kind/enhancement

# see https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates
