{{- if .Values.ingestor.useIngress }}
apiVersion: networking.istio.io/v1
kind: Gateway
metadata:
  annotations:
    cert.gardener.cloud/purpose: managed
{{- if .Values.ingestor.gardenDNSProvider }}
    cert.gardener.cloud/class: garden
    cert.gardener.cloud/dnsrecord-provider-type: {{ .Values.ingestor.gardenDNSProvider.type }}
    cert.gardener.cloud/dnsrecord-secret-ref: {{ .Values.ingestor.gardenDNSProvider.secretRef.namespace }}/{{ .Values.ingestor.gardenDNSProvider.secretRef.name }}
    cert.gardener.cloud/dnsrecord-class: garden
    cert.gardener.cloud/secret-namespace: {{ .Values.ingestor.istioNamespace }}
{{- end }}
  labels:
    app: falco-event-ingestor
  name: falco-event-ingestor-ingress
spec:
  selector:
{{ toYaml .Values.ingestor.istioLabels | indent 4 }}
  servers:
  - hosts:
    - {{ .Values.ingestor.ingressDomain }}
    port:
      name: https
      number: 443
      protocol: HTTPS
    tls:
      mode: SIMPLE
      credentialName: tls-ingestor
{{- end }}
