apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: ingress-to-falco-event-ingestor-from-garden-prometheus
spec:
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: garden
      podSelector:
        matchLabels:
          networking.resources.gardener.cloud/to-all-garden-scrape-targets: allowed
    ports:
    - port: 8080
      protocol: TCP
  podSelector:
    matchLabels:
      app: falco-event-ingestor
  policyTypes:
  - Ingress
