apiVersion: v1
kind: Service
metadata:
  annotations:
    networking.resources.gardener.cloud/from-world-to-ports: '[{"protocol":"TCP","port":3200}]'
    networking.resources.gardener.cloud/from-all-garden-scrape-targets-allowed-ports: '[{"port":8080,"protocol":"TCP"}]'
    networking.resources.gardener.cloud/namespace-selectors: '[{"matchLabels":{"kubernetes.io/metadata.name":"garden"}}]'
    networking.resources.gardener.cloud/pod-label-selector-namespace-alias: extensions
  labels:
    app: falco-event-ingestor
  name: falco-event-ingestor
spec:
  {{- if not .Values.ingestor.useIngress }}
  externalTrafficPolicy: Local
  {{- end}}
  ports:
  - name: ingestor
  {{- if .Values.ingestor.useIngress }}
    port: 3200
    targetPort: 3200
  {{- else }}
    port: 443
    targetPort: 3200
  {{- end }}
  - name: metrics
    port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    app: falco-event-ingestor
  sessionAffinity: None
  {{- if .Values.ingestor.useIngress }}
  type: ClusterIP
  {{- else }}
  type: LoadBalancer
  {{- end }}
